bun:
	bun build ./index_bun.ts --compile --minify --outfile pdr_bun

bun-run:
	bun run ./index_bun.ts

deno:
	deno compile --allow-read --allow-write --output pdr_deno ./index_deno.ts

deno-run:
	deno run --allow-read --allow-write ./index_deno.ts